"use client";

import { useState, useRef, useCallback, useEffect } from "react";
import type { DatasetSummary } from "@/lib/datalab";
import {
  AlertTriangle,
  BarChart3,
  Brain,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Code2,
  Download,
  FlaskConical,
  Lightbulb,
  Loader2,
  Map,
  Rocket,
  Target,
  TrendingUp,
  Zap,
} from "lucide-react";

// ─── Types ────────────────────────────────────────────────────────────────────

type PhaseId =
  | "triage"
  | "stats"
  | "hypotheses"
  | "strategy"
  | "code"
  | "business"
  | "decision";

type PhaseStatus = "idle" | "running" | "done" | "error";

interface PhaseState {
  status: PhaseStatus;
  output: string;
  expanded: boolean;
}

interface PhaseMeta {
  id: PhaseId;
  label: string;
  subtitle: string;
  Icon: React.ElementType;
  color: string;
  bgColor: string;
  borderColor: string;
}

// ─── Phase catalog ────────────────────────────────────────────────────────────

const PHASES: PhaseMeta[] = [
  {
    id: "triage",
    label: "Triage",
    subtitle: "Domain · Quality · Task Detection · Red Flags",
    Icon: AlertTriangle,
    color: "#f59e0b",
    bgColor: "rgba(245,158,11,0.08)",
    borderColor: "rgba(245,158,11,0.45)",
  },
  {
    id: "stats",
    label: "Statistical Analysis",
    subtitle: "Distributions · Outliers · Correlations · Readiness",
    Icon: BarChart3,
    color: "var(--color-cyan-400)",
    bgColor: "rgba(34,211,238,0.07)",
    borderColor: "rgba(34,211,238,0.4)",
  },
  {
    id: "hypotheses",
    label: "Hypothesis Engine",
    subtitle: "5 Testable Business Hypotheses · Ranked by Value",
    Icon: Lightbulb,
    color: "#f472b6",
    bgColor: "rgba(244,114,182,0.07)",
    borderColor: "rgba(244,114,182,0.4)",
  },
  {
    id: "strategy",
    label: "ML Battle Plan",
    subtitle: "Algorithm · Features · Validation · Metrics",
    Icon: Map,
    color: "var(--color-purple-400)",
    bgColor: "rgba(167,139,250,0.07)",
    borderColor: "rgba(167,139,250,0.4)",
  },
  {
    id: "code",
    label: "Production Code",
    subtitle: "Complete Python Pipeline · Runnable · 10 Cells",
    Icon: Code2,
    color: "#67e8f9",
    bgColor: "rgba(103,232,249,0.06)",
    borderColor: "rgba(103,232,249,0.35)",
  },
  {
    id: "business",
    label: "Business Intelligence",
    subtitle: "ROI · Risks · Governance · Quick Wins",
    Icon: TrendingUp,
    color: "#34d399",
    bgColor: "rgba(52,211,153,0.07)",
    borderColor: "rgba(52,211,153,0.4)",
  },
  {
    id: "decision",
    label: "Decision Brief",
    subtitle: "P0/P1/P2 Matrix · Go/No-Go · The One Thing",
    Icon: Target,
    color: "#c4b5fd",
    bgColor: "rgba(196,181,253,0.07)",
    borderColor: "rgba(196,181,253,0.4)",
  },
];

const PHASE_IDS = PHASES.map((p) => p.id);

// ─── Helpers ──────────────────────────────────────────────────────────────────

function initialPhaseStates(): Record<PhaseId, PhaseState> {
  return Object.fromEntries(
    PHASE_IDS.map((id) => [id, { status: "idle" as PhaseStatus, output: "", expanded: false }])
  ) as Record<PhaseId, PhaseState>;
}

/**
 * Build a compact context string from all completed phases before `upToIndex`.
 * Truncates each phase snippet so the total stays under ~1500 chars.
 */
function buildContext(states: Record<PhaseId, PhaseState>, upToIndex: number): string {
  const parts: string[] = [];
  const perPhase = Math.floor(1400 / Math.max(upToIndex, 1));
  for (let i = 0; i < upToIndex; i++) {
    const phase = PHASES[i];
    const out = states[phase.id]?.output ?? "";
    if (!out) continue;
    const snippet = out.slice(0, perPhase).replace(/\n+/g, " ").trim();
    parts.push(`[${phase.label}]: ${snippet}${out.length > perPhase ? "…" : ""}`);
  }
  return parts.join("\n");
}

function buildMarkdownReport(states: Record<PhaseId, PhaseState>, fileName: string): string {
  const sections = PHASES
    .map((p, i) => {
      const { status, output } = states[p.id];
      if (status !== "done" || !output) return null;
      return `## Phase ${i + 1}: ${p.label}\n\n${output}`;
    })
    .filter(Boolean)
    .join("\n\n---\n\n");

  return [
    `# Autonomous Data Science Analysis`,
    ``,
    `**Dataset:** ${fileName}`,
    `**Generated by:** GadaaLabs Autonomous Data Science Agent`,
    `**Date:** ${new Date().toISOString().slice(0, 10)}`,
    ``,
    `---`,
    ``,
    sections,
  ].join("\n");
}

function downloadReport(states: Record<PhaseId, PhaseState>, fileName: string) {
  const md = buildMarkdownReport(states, fileName);
  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${fileName.replace(/\.[^.]+$/, "")}_data_science_analysis.md`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Phase progress tracker ───────────────────────────────────────────────────

function PhaseTracker({
  states,
  currentIndex,
}: {
  states: Record<PhaseId, PhaseState>;
  currentIndex: number;
}) {
  return (
    <div
      className="rounded-xl p-4"
      style={{
        background: "var(--color-bg-surface)",
        border: "1px solid var(--color-border-default)",
      }}
    >
      <div className="flex items-center gap-1 overflow-x-auto pb-1">
        {PHASES.map((phase, i) => {
          const { status } = states[phase.id];
          const Icon = phase.Icon;
          const isDone = status === "done";
          const isActive = status === "running";
          const isError = status === "error";

          return (
            <div key={phase.id} className="flex items-center gap-1 shrink-0">
              <div
                className="flex flex-col items-center gap-1.5 px-2 py-2 rounded-lg transition-all"
                style={{
                  background: isActive
                    ? phase.bgColor
                    : isDone
                    ? "rgba(16,185,129,0.07)"
                    : "transparent",
                  minWidth: 60,
                }}
              >
                <div
                  className="flex h-7 w-7 items-center justify-center rounded-full"
                  style={{
                    background: isDone
                      ? "rgba(16,185,129,0.15)"
                      : isActive
                      ? phase.bgColor
                      : isError
                      ? "rgba(239,68,68,0.12)"
                      : "rgba(60,60,80,0.3)",
                    border: `1px solid ${
                      isDone
                        ? "rgba(16,185,129,0.45)"
                        : isActive
                        ? phase.borderColor
                        : isError
                        ? "rgba(239,68,68,0.35)"
                        : "var(--color-border-subtle)"
                    }`,
                  }}
                >
                  {isActive ? (
                    <Loader2 className="h-3.5 w-3.5 animate-spin" style={{ color: phase.color }} />
                  ) : isDone ? (
                    <CheckCircle2 className="h-3.5 w-3.5" style={{ color: "var(--color-success)" }} />
                  ) : isError ? (
                    <AlertTriangle className="h-3.5 w-3.5" style={{ color: "var(--color-error)" }} />
                  ) : (
                    <Icon
                      className="h-3.5 w-3.5"
                      style={{ color: i <= currentIndex ? "var(--color-text-muted)" : "var(--color-text-disabled)" }}
                    />
                  )}
                </div>
                <span
                  style={{
                    fontSize: 10,
                    fontWeight: 600,
                    color: isDone
                      ? "var(--color-success)"
                      : isActive
                      ? phase.color
                      : isError
                      ? "var(--color-error)"
                      : "var(--color-text-disabled)",
                    textAlign: "center",
                    lineHeight: 1.2,
                    maxWidth: 56,
                  }}
                >
                  {phase.label.split(" ")[0]}
                </span>
              </div>
              {i < PHASES.length - 1 && (
                <div
                  className="h-px shrink-0"
                  style={{
                    width: 12,
                    background: isDone ? "rgba(16,185,129,0.4)" : "var(--color-border-subtle)",
                  }}
                />
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ─── Phase output card ────────────────────────────────────────────────────────

function PhaseCard({
  meta,
  state,
  phaseNumber,
  onToggle,
}: {
  meta: PhaseMeta;
  state: PhaseState;
  phaseNumber: number;
  onToggle: () => void;
}) {
  if (state.status === "idle") return null;

  const { Icon } = meta;
  const isCode = meta.id === "code";
  const isStreaming = state.status === "running";
  const isDone = state.status === "done";
  const isError = state.status === "error";

  const COLLAPSE_THRESHOLD = 400;
  const canToggle = state.output.length > COLLAPSE_THRESHOLD;

  return (
    <div
      className="rounded-xl overflow-hidden"
      style={{
        background: "var(--color-bg-surface)",
        border: "1px solid var(--color-border-default)",
        borderLeft: `3px solid ${
          isDone ? meta.color : isError ? "var(--color-error)" : meta.borderColor
        }`,
      }}
    >
      {/* Header */}
      <div
        className="flex items-center gap-3 px-4 py-3"
        style={{
          background: isStreaming ? meta.bgColor : "transparent",
          borderBottom: "1px solid var(--color-border-subtle)",
        }}
      >
        <div
          className="flex items-center justify-center h-8 w-8 rounded-lg shrink-0"
          style={{ background: meta.bgColor, border: `1px solid ${meta.borderColor}` }}
        >
          {isStreaming ? (
            <Loader2 className="h-4 w-4 animate-spin" style={{ color: meta.color }} />
          ) : (
            <Icon className="h-4 w-4" style={{ color: meta.color }} />
          )}
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-sm font-semibold" style={{ color: "var(--color-text-primary)" }}>
            Phase {phaseNumber} — {meta.label}
          </p>
          <p className="text-xs mt-0.5" style={{ color: "var(--color-text-muted)" }}>
            {meta.subtitle}
          </p>
        </div>
        <span
          className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold shrink-0"
          style={{
            background: isStreaming
              ? meta.bgColor
              : isDone
              ? "rgba(16,185,129,0.12)"
              : isError
              ? "rgba(239,68,68,0.12)"
              : "transparent",
            color: isStreaming
              ? meta.color
              : isDone
              ? "var(--color-success)"
              : isError
              ? "var(--color-error)"
              : "var(--color-text-muted)",
          }}
        >
          {isStreaming && (
            <span
              className="inline-block h-1.5 w-1.5 rounded-full animate-pulse"
              style={{ background: meta.color }}
            />
          )}
          {isDone && <CheckCircle2 className="h-3 w-3" />}
          {isStreaming ? "Live" : isDone ? "Complete" : "Error"}
        </span>
      </div>

      {/* Body */}
      <div
        className="px-4 py-4"
        style={{ position: "relative" }}
      >
        <div
          style={{
            overflow: "hidden",
            maxHeight: state.expanded ? "none" : isCode ? "14em" : "9em",
          }}
        >
          <pre
            className="text-sm leading-relaxed"
            style={{
              color: isError ? "var(--color-error)" : "var(--color-text-secondary)",
              whiteSpace: "pre-wrap",
              fontFamily: isCode
                ? "var(--font-jetbrains, 'JetBrains Mono', monospace)"
                : "var(--font-inter, sans-serif)",
              fontSize: isCode ? "0.78rem" : "0.875rem",
              margin: 0,
            }}
          >
            {state.output}
            {isStreaming && (
              <span className="cursor-blink" style={{ color: meta.color }}>
                ▊
              </span>
            )}
          </pre>
        </div>

        {/* Fade when collapsed */}
        {!state.expanded && canToggle && (
          <div
            style={{
              position: "absolute",
              bottom: 0,
              left: 0,
              right: 0,
              height: 48,
              background: "linear-gradient(to bottom, transparent, var(--color-bg-surface))",
              pointerEvents: "none",
            }}
          />
        )}
      </div>

      {/* Expand/collapse */}
      {canToggle && (
        <button
          onClick={onToggle}
          className="flex items-center justify-center gap-1.5 w-full py-2 text-xs font-medium transition-colors"
          style={{
            borderTop: "1px solid var(--color-border-subtle)",
            color: "var(--color-text-muted)",
            background: "transparent",
          }}
        >
          {state.expanded ? (
            <>
              <ChevronUp className="h-3 w-3" /> Collapse
            </>
          ) : (
            <>
              <ChevronDown className="h-3 w-3" /> Show full output
            </>
          )}
        </button>
      )}
    </div>
  );
}

// ─── Mission complete banner ──────────────────────────────────────────────────

function MissionComplete({ onDownload }: { onDownload: () => void }) {
  return (
    <div
      className="rounded-xl p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"
      style={{
        background: "linear-gradient(135deg, rgba(16,185,129,0.08), rgba(124,58,237,0.08))",
        border: "1px solid rgba(16,185,129,0.3)",
      }}
    >
      <div className="flex items-center gap-3">
        <div
          className="flex h-10 w-10 items-center justify-center rounded-xl shrink-0"
          style={{
            background: "linear-gradient(135deg, rgba(16,185,129,0.2), rgba(124,58,237,0.2))",
            border: "1px solid rgba(16,185,129,0.4)",
          }}
        >
          <Rocket className="h-5 w-5" style={{ color: "var(--color-success)" }} />
        </div>
        <div>
          <p className="font-bold text-sm" style={{ color: "var(--color-success)" }}>
            Mission Complete
          </p>
          <p className="text-xs mt-0.5" style={{ color: "var(--color-text-muted)" }}>
            All 7 autonomous phases finished. Triage → Decision Brief delivered.
          </p>
        </div>
      </div>
      <button
        onClick={onDownload}
        className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold shrink-0 transition-all hover:-translate-y-0.5"
        style={{
          background: "rgba(16,185,129,0.12)",
          border: "1px solid rgba(16,185,129,0.35)",
          color: "var(--color-success)",
        }}
      >
        <Download className="h-4 w-4" />
        Download Full Report (.md)
      </button>
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

export interface DataScienceAgentProps {
  summary: DatasetSummary;
  summaryText: string;
  /** Called when all 7 phases complete successfully */
  onComplete?: () => void;
  /** Called with all phase outputs when all 7 phases complete */
  onPhasesComplete?: (outputs: Record<string, string>) => void;
}

export function DataScienceAgent({ summary, summaryText, onComplete, onPhasesComplete }: DataScienceAgentProps) {
  const [phaseStates, setPhaseStates] = useState<Record<PhaseId, PhaseState>>(initialPhaseStates);
  const [running, setRunning] = useState(false);
  const [done, setDone] = useState(false);
  const [currentPhaseIndex, setCurrentPhaseIndex] = useState(-1);
  const [fatalError, setFatalError] = useState<string | null>(null);

  // Ref mirrors state for stale-closure-safe reads inside async callbacks
  const statesRef = useRef<Record<PhaseId, PhaseState>>(initialPhaseStates());
  const abortRef = useRef<AbortController | null>(null);

  // ── Notify parent when done ────────────────────────────────────────────────
  useEffect(() => {
    if (done && onComplete) {
      onComplete();
    }
    if (done && onPhasesComplete) {
      const outputs = Object.fromEntries(
        PHASE_IDS.map(id => [id, statesRef.current[id].output])
      ) as Record<string, string>;
      onPhasesComplete(outputs);
    }
  }, [done, onComplete, onPhasesComplete]);

  // ── State helper ───────────────────────────────────────────────────────────
  const setPhase = useCallback((id: PhaseId, patch: Partial<PhaseState>) => {
    setPhaseStates((prev) => {
      const next = { ...prev, [id]: { ...prev[id], ...patch } };
      statesRef.current = next;
      return next;
    });
  }, []);

  const toggleExpand = useCallback((id: PhaseId) => {
    setPhaseStates((prev) => ({
      ...prev,
      [id]: { ...prev[id], expanded: !prev[id].expanded },
    }));
  }, []);

  // ── Pipeline runner ────────────────────────────────────────────────────────
  const runPipeline = useCallback(async () => {
    if (running) return;

    const fresh = initialPhaseStates();
    setPhaseStates(fresh);
    statesRef.current = fresh;
    setRunning(true);
    setDone(false);
    setFatalError(null);
    setCurrentPhaseIndex(0);

    abortRef.current = new AbortController();

    try {
      for (let i = 0; i < PHASES.length; i++) {
        const phase = PHASES[i];
        setCurrentPhaseIndex(i);

        const context = buildContext(statesRef.current, i);
        setPhase(phase.id, { status: "running", output: "" });

        let accumulated = "";

        try {
          const res = await fetch("/api/ai/data-science-agent", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ summaryText, phase: phase.id, context }),
            signal: abortRef.current.signal,
          });

          if (!res.ok) {
            const errData = await res.json().catch(() => ({ error: `HTTP ${res.status}` }));
            throw new Error((errData as { error?: string }).error ?? `HTTP ${res.status}`);
          }

          if (!res.body) throw new Error("No response stream");

          const reader = res.body.getReader();
          const decoder = new TextDecoder();

          while (true) {
            const { done: streamDone, value } = await reader.read();
            if (streamDone) break;
            accumulated += decoder.decode(value, { stream: true });
            setPhase(phase.id, { output: accumulated });
          }

          setPhase(phase.id, { status: "done", output: accumulated });
        } catch (e) {
          if ((e as Error).name === "AbortError") {
            setPhase(phase.id, { status: "error", output: "Analysis cancelled." });
            return;
          }
          const msg = (e as Error).message ?? "Unknown error";
          setPhase(phase.id, { status: "error", output: `Phase failed: ${msg}` });
          setFatalError(`Phase "${phase.label}" failed: ${msg}`);
          return;
        }
      }

      setDone(true);
    } finally {
      setRunning(false);
      setCurrentPhaseIndex(-1);
    }
  }, [running, summaryText, setPhase]);

  const handleCancel = useCallback(() => {
    abortRef.current?.abort();
  }, []);

  // ── Derived ────────────────────────────────────────────────────────────────
  const completedCount = PHASE_IDS.filter((id) => phaseStates[id].status === "done").length;
  const hasStarted = PHASE_IDS.some((id) => phaseStates[id].status !== "idle");

  // ── Render ─────────────────────────────────────────────────────────────────
  return (
    <div className="space-y-4">

      {/* ── Agent header ── */}
      <div
        className="rounded-xl px-5 py-4 flex flex-wrap items-center justify-between gap-4"
        style={{
          background: "var(--color-bg-surface)",
          border: "1px solid var(--color-border-default)",
        }}
      >
        <div className="flex items-center gap-3">
          <div
            className="flex h-9 w-9 items-center justify-center rounded-xl shrink-0"
            style={{
              background: "linear-gradient(135deg, var(--color-purple-600), var(--color-cyan-500))",
            }}
          >
            <Brain className="h-4 w-4 text-white" />
          </div>
          <div>
            <p className="font-bold text-sm" style={{ color: "var(--color-text-primary)" }}>
              Autonomous Data Science Agent
            </p>
            <p className="text-xs mt-0.5" style={{ color: "var(--color-text-muted)" }}>
              {!hasStarted
                ? "7-phase pipeline — Triage → Stats → Hypotheses → Strategy → Code → Business → Decision"
                : done
                ? "All 7 phases complete"
                : running
                ? `Phase ${currentPhaseIndex + 1} of 7 — ${PHASES[currentPhaseIndex]?.label ?? "…"}`
                : `${completedCount} of 7 phases complete`}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {running && (
            <button
              onClick={handleCancel}
              className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-semibold"
              style={{
                background: "rgba(239,68,68,0.08)",
                border: "1px solid rgba(239,68,68,0.25)",
                color: "var(--color-error)",
              }}
            >
              Cancel
            </button>
          )}
          {!running && (
            <button
              onClick={runPipeline}
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold transition-all hover:-translate-y-0.5"
              style={{
                background: "linear-gradient(135deg, var(--color-purple-600), var(--color-purple-500))",
                color: "#fff",
                boxShadow: "var(--glow-purple-sm)",
              }}
            >
              <Zap className="h-4 w-4" />
              {done ? "Re-run Analysis" : hasStarted ? "Retry" : "Launch 7-Phase Analysis"}
            </button>
          )}
        </div>
      </div>

      {/* ── Phase tracker (appears once started) ── */}
      {hasStarted && (
        <PhaseTracker states={phaseStates} currentIndex={currentPhaseIndex} />
      )}

      {/* ── Fatal error notice ── */}
      {fatalError && (
        <div
          className="rounded-xl px-4 py-3 flex items-start gap-2"
          style={{
            background: "rgba(239,68,68,0.08)",
            border: "1px solid rgba(239,68,68,0.25)",
          }}
        >
          <AlertTriangle
            className="h-4 w-4 mt-0.5 shrink-0"
            style={{ color: "var(--color-error)" }}
          />
          <p className="text-sm" style={{ color: "var(--color-error)" }}>
            {fatalError}
          </p>
        </div>
      )}

      {/* ── Empty state ── */}
      {!hasStarted && (
        <div
          className="rounded-xl p-10 text-center"
          style={{
            background: "var(--color-bg-surface)",
            border: "1px solid var(--color-border-default)",
          }}
        >
          <FlaskConical
            className="h-12 w-12 mx-auto mb-4"
            style={{ color: "var(--color-text-disabled)" }}
          />
          <p className="font-semibold text-sm mb-2" style={{ color: "var(--color-text-secondary)" }}>
            Mission Control — Ready
          </p>
          <p
            className="text-xs max-w-md mx-auto mb-6 leading-relaxed"
            style={{ color: "var(--color-text-muted)" }}
          >
            7 autonomous phases run sequentially — each phase builds on the decisions of the last.
            Triage → Statistical Analysis → Hypothesis Engine → ML Battle Plan →
            Production Code → Business Intelligence → Decision Brief.
          </p>
          <button
            onClick={runPipeline}
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-semibold"
            style={{
              background: "linear-gradient(135deg, var(--color-purple-600), var(--color-purple-500))",
              color: "#fff",
              boxShadow: "var(--glow-purple-sm)",
            }}
          >
            <Zap className="h-4 w-4" />
            Launch Mission
          </button>
        </div>
      )}

      {/* ── Phase output cards ── */}
      {PHASES.map((meta, i) => (
        <PhaseCard
          key={meta.id}
          meta={meta}
          state={phaseStates[meta.id]}
          phaseNumber={i + 1}
          onToggle={() => toggleExpand(meta.id)}
        />
      ))}

      {/* ── Mission complete banner ── */}
      {done && (
        <MissionComplete
          onDownload={() => downloadReport(phaseStates, summary.fileName)}
        />
      )}
    </div>
  );
}
