"use client";

import { Download } from "lucide-react";
import type { DatasetSummary } from "@/lib/datalab";

interface Props {
  report: string;
  summary: DatasetSummary;
}

export function ReportDownload({ report, summary }: Props) {
  const download = () => {
    const date = new Date().toISOString().slice(0, 10);
    const name = summary.fileName.replace(/\.[^.]+$/, "");
    const content = `# EDA Report: ${summary.fileName}\nGenerated by GadaaLabs DataLab · ${date}\n\n---\n\n${report}`;
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `gadaalabs-eda-${name}-${date}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={download}
      className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold transition-all"
      style={{
        background: "rgba(6,182,212,0.1)",
        border: "1px solid rgba(6,182,212,0.3)",
        color: "var(--color-cyan-400)",
      }}
    >
      <Download className="h-4 w-4" />
      Download Report (.md)
    </button>
  );
}
