"use client";

import { Download, FileText, Lock } from "lucide-react";
import type { DatasetSummary } from "@/lib/datalab";

const PHASE_META: { id: string; label: string; color: string }[] = [
  { id: "triage",      label: "Phase 1 — Triage",                color: "#f59e0b" },
  { id: "stats",       label: "Phase 2 — Statistical Analysis",  color: "#06b6d4" },
  { id: "hypotheses",  label: "Phase 3 — Hypothesis Engine",     color: "#f472b6" },
  { id: "strategy",    label: "Phase 4 — ML Battle Plan",        color: "#a78bfa" },
  { id: "code",        label: "Phase 5 — Production Code",       color: "#67e8f9" },
  { id: "business",    label: "Phase 6 — Business Intelligence", color: "#34d399" },
  { id: "decision",    label: "Phase 7 — Decision Brief",        color: "#c4b5fd" },
];

function buildTechMarkdown(outputs: Record<string, string>, summary: DatasetSummary): string {
  const lines: string[] = [
    `# Technical Data Science Report`,
    ``,
    `**Dataset:** ${summary.fileName}`,
    `**Rows:** ${summary.rowCount.toLocaleString()} · **Columns:** ${summary.columnCount}`,
    `**File size:** ${summary.fileSizeKB} KB`,
    `**Generated by:** GadaaLabs Autonomous Data Science Agent — 7-Phase Pipeline`,
    `**Date:** ${new Date().toISOString().slice(0, 10)}`,
    ``,
    `---`,
    ``,
    `## Dataset Schema`,
    ``,
    `| Column | Type | Non-null | Unique | Mean / Top Value |`,
    `|--------|------|----------|--------|-----------------|`,
    ...summary.columns.map(c => {
      const val = c.type === "numeric"
        ? (c.mean !== undefined ? c.mean.toFixed(4) : "—")
        : c.topValues?.[0]?.value ?? "—";
      return `| \`${c.name}\` | ${c.type} | ${(100 - c.nullPct).toFixed(1)}% | ${c.unique} | ${val} |`;
    }),
    ``,
    `---`,
    ``,
  ];

  for (const meta of PHASE_META) {
    const out = outputs[meta.id];
    if (!out) continue;
    lines.push(`## ${meta.label}`, ``, out, ``, `---`, ``);
  }

  lines.push(`*Report generated by GadaaLabs Autonomous Data Science Agent*`);
  return lines.join("\n");
}

function downloadMd(content: string, fileName: string) {
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(url);
}

interface Props {
  outputs: Record<string, string> | null;
  summary: DatasetSummary;
}

export function TechReport({ outputs, summary }: Props) {
  if (!outputs) {
    return (
      <div className="rounded-xl p-10 text-center"
        style={{ background: "var(--color-bg-surface)", border: "1px solid var(--color-border-default)" }}>
        <Lock className="h-10 w-10 mx-auto mb-4" style={{ color: "var(--color-text-disabled)" }} />
        <p className="font-semibold text-sm mb-2" style={{ color: "var(--color-text-secondary)" }}>
          No Analysis Yet
        </p>
        <p className="text-xs max-w-sm mx-auto" style={{ color: "var(--color-text-muted)" }}>
          Run the 7-phase Data Science Agent analysis first. The Technical Report will be generated automatically when all phases complete.
        </p>
      </div>
    );
  }

  const completedPhases = PHASE_META.filter(m => outputs[m.id]);
  const md = buildTechMarkdown(outputs, summary);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="rounded-xl px-5 py-4 flex flex-wrap items-center justify-between gap-4"
        style={{ background: "var(--color-bg-surface)", border: "1px solid var(--color-border-default)" }}>
        <div className="flex items-center gap-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-xl shrink-0"
            style={{ background: "linear-gradient(135deg, #7c3aed, #06b6d4)" }}>
            <FileText className="h-4 w-4 text-white" />
          </div>
          <div>
            <p className="font-bold text-sm" style={{ color: "var(--color-text-primary)" }}>Technical Report</p>
            <p className="text-xs mt-0.5" style={{ color: "var(--color-text-muted)" }}>
              {completedPhases.length} of 7 phases · For DS/ML engineers and data scientists
            </p>
          </div>
        </div>
        <button
          onClick={() => downloadMd(md, `${summary.fileName.replace(/\.[^.]+$/, "")}_technical_report.md`)}
          className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold transition-all hover:-translate-y-0.5"
          style={{ background: "rgba(124,58,237,0.12)", border: "1px solid rgba(124,58,237,0.35)", color: "var(--color-purple-400)" }}>
          <Download className="h-4 w-4" />
          Download .md
        </button>
      </div>

      {/* Schema */}
      <div className="rounded-xl overflow-hidden"
        style={{ background: "var(--color-bg-elevated)", border: "1px solid var(--color-border-default)" }}>
        <div className="px-4 py-3" style={{ borderBottom: "1px solid var(--color-border-subtle)" }}>
          <p className="text-xs font-semibold uppercase tracking-widest" style={{ color: "var(--color-text-muted)" }}>
            Dataset Schema — {summary.fileName}
          </p>
        </div>
        <div className="p-4 overflow-x-auto">
          <table className="w-full text-xs" style={{ borderCollapse: "collapse" }}>
            <thead>
              <tr style={{ borderBottom: "1px solid var(--color-border-subtle)" }}>
                {["Column", "Type", "Non-null %", "Unique", "Mean / Top Value"].map(h => (
                  <th key={h} className="text-left pb-2 pr-4 font-semibold uppercase tracking-wide"
                    style={{ color: "var(--color-text-muted)", fontSize: 10 }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {summary.columns.map(c => (
                <tr key={c.name} style={{ borderBottom: "1px solid var(--color-border-subtle)" }}>
                  <td className="py-1.5 pr-4 font-mono font-semibold" style={{ color: "var(--color-text-primary)" }}>{c.name}</td>
                  <td className="py-1.5 pr-4" style={{ color: "var(--color-text-muted)" }}>{c.type}</td>
                  <td className="py-1.5 pr-4" style={{
                    color: c.nullPct > 20 ? "#ef4444" : c.nullPct > 5 ? "#f59e0b" : "#10b981",
                    fontWeight: 600,
                  }}>{(100 - c.nullPct).toFixed(1)}%</td>
                  <td className="py-1.5 pr-4" style={{ color: "var(--color-text-secondary)" }}>{c.unique.toLocaleString()}</td>
                  <td className="py-1.5 font-mono" style={{ color: "var(--color-text-secondary)" }}>
                    {c.type === "numeric"
                      ? (c.mean !== undefined ? c.mean.toFixed(4) : "—")
                      : c.topValues?.[0]?.value ?? "—"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Phase outputs */}
      {PHASE_META.map(meta => {
        const out = outputs[meta.id];
        if (!out) return null;
        const isCode = meta.id === "code";
        return (
          <div key={meta.id} className="rounded-xl overflow-hidden"
            style={{ background: "var(--color-bg-surface)", border: "1px solid var(--color-border-default)", borderLeft: `3px solid ${meta.color}` }}>
            <div className="px-4 py-3" style={{ borderBottom: "1px solid var(--color-border-subtle)" }}>
              <p className="text-sm font-semibold" style={{ color: meta.color }}>{meta.label}</p>
            </div>
            <div className="px-4 py-4">
              <pre
                className="text-sm leading-relaxed"
                style={{
                  color: "var(--color-text-secondary)",
                  whiteSpace: "pre-wrap",
                  fontFamily: isCode ? "var(--font-jetbrains, 'JetBrains Mono', monospace)" : "var(--font-inter, sans-serif)",
                  fontSize: isCode ? "0.78rem" : "0.875rem",
                  margin: 0,
                }}>
                {out}
              </pre>
            </div>
          </div>
        );
      })}
    </div>
  );
}
