"use client";

import dynamic from "next/dynamic";
import { Download, FileText, Lock, BookOpen } from "lucide-react";
import type { DatasetSummary } from "@/lib/datalab";

// Completely isolated — no static import of @react-pdf/renderer in this module graph
const TechReportPDFButton = dynamic(() => import("./TechReportPDFButton"), { ssr: false });

const PHASE_META: { id: string; label: string; color: string }[] = [
  { id: "triage",      label: "Phase 1 — Triage",                color: "#f59e0b" },
  { id: "stats",       label: "Phase 2 — Statistical Analysis",  color: "#06b6d4" },
  { id: "hypotheses",  label: "Phase 3 — Hypothesis Engine",     color: "#f472b6" },
  { id: "strategy",    label: "Phase 4 — ML Battle Plan",        color: "#a78bfa" },
  { id: "code",        label: "Phase 5 — Production Code",       color: "#67e8f9" },
  { id: "business",    label: "Phase 6 — Business Intelligence", color: "#34d399" },
  { id: "decision",    label: "Phase 7 — Decision Brief",        color: "#c4b5fd" },
];

function buildTechMarkdown(outputs: Record<string, string>, summary: DatasetSummary): string {
  const lines: string[] = [
    `# Technical Data Science Report`,
    ``,
    `**Dataset:** ${summary.fileName}`,
    `**Rows:** ${summary.rowCount.toLocaleString()} · **Columns:** ${summary.columnCount}`,
    `**File size:** ${summary.fileSizeKB} KB`,
    `**Generated by:** GadaaLabs Autonomous Data Science Agent — 7-Phase Pipeline`,
    `**Date:** ${new Date().toISOString().slice(0, 10)}`,
    ``,
    `---`,
    ``,
    `## Dataset Schema`,
    ``,
    `| Column | Type | Non-null | Unique | Mean / Top Value |`,
    `|--------|------|----------|--------|-----------------|`,
    ...summary.columns.map(c => {
      const val = c.type === "numeric"
        ? (c.mean !== undefined ? c.mean.toFixed(4) : "—")
        : c.topValues?.[0]?.value ?? "—";
      return `| \`${c.name}\` | ${c.type} | ${(100 - c.nullPct).toFixed(1)}% | ${c.unique} | ${val} |`;
    }),
    ``,
    `---`,
    ``,
  ];

  for (const meta of PHASE_META) {
    const out = outputs[meta.id];
    if (!out) continue;
    lines.push(`## ${meta.label}`, ``, out, ``, `---`, ``);
  }

  lines.push(`*Report generated by GadaaLabs Autonomous Data Science Agent*`);
  return lines.join("\n");
}

function downloadMd(content: string, fileName: string) {
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Jupyter Notebook builder ─────────────────────────────────────────────────

type NbSource = string[];
interface CodeCell   { cell_type: "code";     id: string; metadata: object; source: NbSource; outputs: unknown[]; execution_count: null }
interface MdCell     { cell_type: "markdown"; id: string; metadata: object; source: NbSource }
type NbCell = CodeCell | MdCell;

let _cellId = 0;
const cid = () => `cell-${(++_cellId).toString().padStart(3, "0")}`;
const src  = (lines: string[]): NbSource => lines.map((l, i) => i < lines.length - 1 ? l + "\n" : l);

function code(lines: string[]): CodeCell {
  return { cell_type: "code", id: cid(), metadata: {}, source: src(lines), outputs: [], execution_count: null };
}
function md(lines: string[]): MdCell {
  return { cell_type: "markdown", id: cid(), metadata: {}, source: src(lines) };
}

function buildNotebook(outputs: Record<string, string>, summary: DatasetSummary): string {
  _cellId = 0;
  const date = new Date().toISOString().slice(0, 10);
  const numCols = summary.columns.filter(c => c.type === "numeric").map(c => c.name);
  const catCols = summary.columns.filter(c => c.type === "categorical").map(c => c.name);
  const baseName = summary.fileName.replace(/\.[^.]+$/, "");

  const cells: NbCell[] = [
    // Title
    md([
      `# Data Science Report — ${summary.fileName}`,
      ``,
      `**Generated by:** GadaaLabs Autonomous Data Science Agent (7-Phase Pipeline)`,
      `**Date:** ${date}`,
      `**Dataset:** ${summary.rowCount.toLocaleString()} rows × ${summary.columnCount} columns · ${summary.fileSizeKB} KB`,
      ``,
      `---`,
    ]),

    // Imports
    code([
      `import pandas as pd`,
      `import numpy as np`,
      `import matplotlib.pyplot as plt`,
      `import seaborn as sns`,
      `from sklearn.model_selection import train_test_split`,
      `from sklearn.preprocessing import StandardScaler, LabelEncoder`,
      `from sklearn.metrics import classification_report, mean_squared_error, r2_score`,
      ``,
      `plt.style.use('dark_background')`,
      `pd.set_option('display.max_columns', None)`,
    ]),

    // Load data
    code([
      `# Load dataset`,
      `# Replace the path below with your actual file path`,
      `df = pd.read_csv("${summary.fileName}")`,
      `print(f"Shape: {df.shape}")`,
      `df.head()`,
    ]),

    // Basic EDA
    code([
      `# Dataset info`,
      `df.info()`,
    ]),
    code([
      `# Descriptive statistics`,
      `df.describe(include='all').T`,
    ]),

    // Null analysis
    code([
      `# Null analysis`,
      `null_stats = pd.DataFrame({`,
      `    'missing': df.isnull().sum(),`,
      `    'missing_pct': (df.isnull().sum() / len(df) * 100).round(2)`,
      `}).query('missing > 0').sort_values('missing_pct', ascending=False)`,
      `print(null_stats.to_string())`,
    ]),

    // Distributions
    ...(numCols.length > 0 ? [code([
      `# Numeric distributions`,
      `num_cols = ${JSON.stringify(numCols.slice(0, 8))}`,
      `fig, axes = plt.subplots(`,
      `    nrows=max(1, len(num_cols) // 4 + (1 if len(num_cols) % 4 else 0)),`,
      `    ncols=min(4, len(num_cols)),`,
      `    figsize=(16, max(4, len(num_cols)))`,
      `)`,
      `axes = np.array(axes).flatten()`,
      `for i, col in enumerate(num_cols):`,
      `    df[col].hist(bins=30, ax=axes[i], color='#7c3aed', alpha=0.8)`,
      `    axes[i].set_title(col, fontsize=10)`,
      `for ax in axes[len(num_cols):]:`,
      `    ax.set_visible(False)`,
      `plt.tight_layout()`,
      `plt.show()`,
    ])] : []),

    // Correlation heatmap
    ...(numCols.length > 1 ? [code([
      `# Correlation heatmap`,
      `corr_cols = ${JSON.stringify(numCols.slice(0, 15))}`,
      `corr = df[corr_cols].corr()`,
      `plt.figure(figsize=(max(8, len(corr_cols)), max(6, len(corr_cols) - 1)))`,
      `sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', center=0)`,
      `plt.title('Pearson Correlation Matrix')`,
      `plt.tight_layout()`,
      `plt.show()`,
    ])] : []),

    // Categorical plots
    ...(catCols.length > 0 ? [code([
      `# Categorical distributions (top 4 columns)`,
      `cat_cols = ${JSON.stringify(catCols.slice(0, 4))}`,
      `fig, axes = plt.subplots(1, len(cat_cols), figsize=(5 * len(cat_cols), 4))`,
      `if len(cat_cols) == 1: axes = [axes]`,
      `for ax, col in zip(axes, cat_cols):`,
      `    vc = df[col].value_counts().head(10)`,
      `    vc.plot(kind='barh', ax=ax, color='#06b6d4')`,
      `    ax.set_title(col, fontsize=10)`,
      `plt.tight_layout()`,
      `plt.show()`,
    ])] : []),
  ];

  // Phase outputs as markdown + phase 5 code as code cell
  for (const meta of PHASE_META) {
    const out = outputs[meta.id];
    if (!out) continue;
    if (meta.id === "code") {
      cells.push(md([`## ${meta.label}`]));
      cells.push(code(out.split("\n")));
    } else {
      cells.push(md([`## ${meta.label}`, ``, out]));
    }
  }

  cells.push(md([`---`, `*Generated by GadaaLabs · ${date}*`]));

  const nb = {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: { display_name: "Python 3", language: "python", name: "python3" },
      language_info: { name: "python", version: "3.11.0" },
    },
    cells,
  };

  return JSON.stringify(nb, null, 2);
}

function downloadNotebook(content: string, fileName: string) {
  const a = document.createElement("a");
  a.href = URL.createObjectURL(new Blob([content], { type: "application/x-ipynb+json" }));
  a.download = fileName;
  a.click();
}

interface Props {
  outputs: Record<string, string> | null;
  summary: DatasetSummary;
}

export function TechReport({ outputs, summary }: Props) {
  if (!outputs) {
    return (
      <div className="rounded-xl p-10 text-center"
        style={{ background: "var(--color-bg-surface)", border: "1px solid var(--color-border-default)" }}>
        <Lock className="h-10 w-10 mx-auto mb-4" style={{ color: "var(--color-text-disabled)" }} />
        <p className="font-semibold text-sm mb-2" style={{ color: "var(--color-text-secondary)" }}>
          No Analysis Yet
        </p>
        <p className="text-xs max-w-sm mx-auto" style={{ color: "var(--color-text-muted)" }}>
          Run the 7-phase Data Science Agent analysis first. The Technical Report will be generated automatically when all phases complete.
        </p>
      </div>
    );
  }

  const completedPhases = PHASE_META.filter(m => outputs[m.id]);
  const markdownContent = buildTechMarkdown(outputs, summary);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="rounded-xl px-5 py-4 flex flex-wrap items-center justify-between gap-4"
        style={{ background: "var(--color-bg-surface)", border: "1px solid var(--color-border-default)" }}>
        <div className="flex items-center gap-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-xl shrink-0"
            style={{ background: "linear-gradient(135deg, #7c3aed, #06b6d4)" }}>
            <FileText className="h-4 w-4 text-white" />
          </div>
          <div>
            <p className="font-bold text-sm" style={{ color: "var(--color-text-primary)" }}>Technical Report</p>
            <p className="text-xs mt-0.5" style={{ color: "var(--color-text-muted)" }}>
              {completedPhases.length} of 7 phases · For DS/ML engineers and data scientists
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <TechReportPDFButton outputs={outputs} summary={summary} />
          <button
            onClick={() => downloadNotebook(buildNotebook(outputs, summary), `${summary.fileName.replace(/\.[^.]+$/, "")}_analysis.ipynb`)}
            className="inline-flex items-center gap-2 px-3 py-2 rounded-xl text-xs font-semibold"
            style={{ background: "rgba(6,182,212,0.1)", border: "1px solid rgba(6,182,212,0.35)", color: "#06b6d4" }}>
            <BookOpen className="h-3.5 w-3.5" />
            .ipynb
          </button>
          <button
            onClick={() => downloadMd(markdownContent, `${summary.fileName.replace(/\.[^.]+$/, "")}_technical_report.md`)}
            className="inline-flex items-center gap-2 px-3 py-2 rounded-xl text-xs font-semibold"
            style={{ background: "var(--color-bg-elevated)", border: "1px solid var(--color-border-default)", color: "var(--color-text-muted)" }}>
            <Download className="h-3.5 w-3.5" />
            .md
          </button>
        </div>
      </div>

      {/* Schema */}
      <div className="rounded-xl overflow-hidden"
        style={{ background: "var(--color-bg-elevated)", border: "1px solid var(--color-border-default)" }}>
        <div className="px-4 py-3" style={{ borderBottom: "1px solid var(--color-border-subtle)" }}>
          <p className="text-xs font-semibold uppercase tracking-widest" style={{ color: "var(--color-text-muted)" }}>
            Dataset Schema — {summary.fileName}
          </p>
        </div>
        <div className="p-4 overflow-x-auto">
          <table className="w-full text-xs" style={{ borderCollapse: "collapse" }}>
            <thead>
              <tr style={{ borderBottom: "1px solid var(--color-border-subtle)" }}>
                {["Column", "Type", "Non-null %", "Unique", "Mean / Top Value"].map(h => (
                  <th key={h} className="text-left pb-2 pr-4 font-semibold uppercase tracking-wide"
                    style={{ color: "var(--color-text-muted)", fontSize: 10 }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {summary.columns.map(c => (
                <tr key={c.name} style={{ borderBottom: "1px solid var(--color-border-subtle)" }}>
                  <td className="py-1.5 pr-4 font-mono font-semibold" style={{ color: "var(--color-text-primary)" }}>{c.name}</td>
                  <td className="py-1.5 pr-4" style={{ color: "var(--color-text-muted)" }}>{c.type}</td>
                  <td className="py-1.5 pr-4" style={{
                    color: c.nullPct > 20 ? "#ef4444" : c.nullPct > 5 ? "#f59e0b" : "#10b981",
                    fontWeight: 600,
                  }}>{(100 - c.nullPct).toFixed(1)}%</td>
                  <td className="py-1.5 pr-4" style={{ color: "var(--color-text-secondary)" }}>{c.unique.toLocaleString()}</td>
                  <td className="py-1.5 font-mono" style={{ color: "var(--color-text-secondary)" }}>
                    {c.type === "numeric"
                      ? (c.mean !== undefined ? c.mean.toFixed(4) : "—")
                      : c.topValues?.[0]?.value ?? "—"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Phase outputs */}
      {PHASE_META.map(meta => {
        const out = outputs[meta.id];
        if (!out) return null;
        const isCode = meta.id === "code";
        return (
          <div key={meta.id} className="rounded-xl overflow-hidden"
            style={{ background: "var(--color-bg-surface)", border: "1px solid var(--color-border-default)", borderLeft: `3px solid ${meta.color}` }}>
            <div className="px-4 py-3" style={{ borderBottom: "1px solid var(--color-border-subtle)" }}>
              <p className="text-sm font-semibold" style={{ color: meta.color }}>{meta.label}</p>
            </div>
            <div className="px-4 py-4">
              <pre
                className="text-sm leading-relaxed"
                style={{
                  color: "var(--color-text-secondary)",
                  whiteSpace: "pre-wrap",
                  fontFamily: isCode ? "var(--font-jetbrains, 'JetBrains Mono', monospace)" : "var(--font-inter, sans-serif)",
                  fontSize: isCode ? "0.78rem" : "0.875rem",
                  margin: 0,
                }}>
                {out}
              </pre>
            </div>
          </div>
        );
      })}
    </div>
  );
}
