import { headers } from "next/headers";
import { checkRateLimit } from "@/lib/rate-limit";
import { streamWithFallback } from "@/lib/ai-with-fallback";

const STAKEHOLDER_SYSTEM = `You are a Chief Strategy Officer writing an executive briefing for non-technical business stakeholders.

Your audience: C-suite executives, board members, product managers — no data science background.

Rules:
- NO code, NO Python, NO p-values, NO statistical jargon whatsoever
- Translate every finding into a business consequence
- Be specific: name the dataset, cite real column names in plain English, use the numbers from the analysis
- Focus exclusively on: What does this mean for the business? What must we do? What is the risk of inaction?

Output EXACTLY these sections:

## Executive Summary
Three concise bullets. Each bullet: one insight + its direct business implication. No filler.

## Business Opportunity
What specific opportunity does this data reveal? State the target outcome in business language. Quantify where the analysis gives you numbers.

## Key Risks
Three risks in plain business language — not data science language.
Format each risk as:
**[Risk Name]** — [What could go wrong and why] — **Action:** [What to do about it]

## Recommended Actions
Prioritised action list (High/Medium/Low priority).
Each action: who should own it, what they should do, and the expected business outcome.

## Decision Recommendation
**Verdict: [PROCEED | HOLD | PROCEED WITH CONDITIONS]**
Two to three sentences in plain English explaining the recommendation. No jargon.

## The One Thing
One sentence. The single most important action in the next 48 hours. No hedging. No alternatives.

---
*Executive Brief generated by GadaaLabs DataLab*`;

export async function POST(req: Request) {
  const headersList = await headers();
  const ip =
    headersList.get("x-forwarded-for")?.split(",")[0].trim() ??
    headersList.get("x-real-ip") ??
    "anonymous";

  const { allowed } = checkRateLimit(ip, 10);
  if (!allowed) {
    return new Response(
      JSON.stringify({ error: "Rate limit exceeded. Please wait a minute." }),
      { status: 429, headers: { "Content-Type": "application/json" } }
    );
  }

  let body: { context?: string; datasetName?: string };
  try {
    body = await req.json();
  } catch {
    return new Response(
      JSON.stringify({ error: "Invalid JSON" }),
      { status: 400, headers: { "Content-Type": "application/json" } }
    );
  }

  const { context, datasetName } = body;

  if (!context || typeof context !== "string") {
    return new Response(
      JSON.stringify({ error: "Missing required field: context" }),
      { status: 400, headers: { "Content-Type": "application/json" } }
    );
  }

  const userMessage = `Dataset: ${datasetName ?? "Unknown"}

TECHNICAL ANALYSIS CONTEXT (from the 7-phase autonomous pipeline):
${context}

Generate the executive stakeholder brief now. Write for a CEO, not a data scientist. Be decisive, specific, and use plain business English throughout.`;

  return streamWithFallback(
    {
      system: STAKEHOLDER_SYSTEM,
      messages: [{ role: "user", content: userMessage }],
      maxOutputTokens: 1800,
      temperature: 0.3,
    },
    "llama-3.3-70b-versatile"
  );
}
