import type { DatasetSummary } from "./datalab";

interface NotebookCell {
  cell_type: "markdown" | "code";
  source: string[];
  metadata: Record<string, unknown>;
  outputs?: unknown[];
  execution_count?: number | null;
}

function md(source: string): NotebookCell {
  return { cell_type: "markdown", source: source.split("\n").map((l, i, a) => i < a.length - 1 ? l + "\n" : l), metadata: {} };
}

function code(source: string): NotebookCell {
  return { cell_type: "code", source: source.split("\n").map((l, i, a) => i < a.length - 1 ? l + "\n" : l), metadata: {}, outputs: [], execution_count: null };
}

export function buildNotebook(summary: DatasetSummary, aiCode: string, report: string): string {
  const numericCols = summary.columns.filter((c) => c.type === "numeric").map((c) => c.name);
  const catCols = summary.columns.filter((c) => c.type === "categorical").map((c) => c.name);
  const highNullCols = summary.columns.filter((c) => c.nullPct > 20).map((c) => c.name);

  const cells: NotebookCell[] = [
    md(`# ${summary.fileName} — Data Science Analysis\n\n> Generated by [GadaaLabs DataLab](https://gadaalabs.com/datalab)\n\n**Dataset:** ${summary.fileName}  \n**Rows:** ${summary.rowCount.toLocaleString()}  \n**Columns:** ${summary.columnCount}  \n**File size:** ${summary.fileSizeKB} KB`),

    code(`# ── Setup ──────────────────────────────────────────────────────────
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.4f}".format)
sns.set_theme(style="darkgrid", palette="muted")
plt.rcParams["figure.dpi"] = 120
print("Libraries loaded ✓")`),

    code(`# ── Load data ───────────────────────────────────────────────────────
# Replace the path below with your actual file path
df = pd.read_csv("${summary.fileName}")   # or pd.read_excel(...)
print(f"Shape: {df.shape}")
df.head()`),

    md(`## 1. Dataset Profile`),

    code(`# ── Profile ─────────────────────────────────────────────────────────
print("=== Data Types ===")
print(df.dtypes)
print(f"\\n=== Memory Usage: {df.memory_usage(deep=True).sum() / 1024:.1f} KB ===")
print("\\n=== First look ===")
df.describe(include="all").T`),

    md(`## 2. Missing Value Analysis`),

    code(`# ── Missing values ──────────────────────────────────────────────────
null_report = pd.DataFrame({
    "missing": df.isnull().sum(),
    "pct": (df.isnull().mean() * 100).round(2),
}).sort_values("pct", ascending=False)
null_report = null_report[null_report["missing"] > 0]

if null_report.empty:
    print("No missing values ✓")
else:
    print(null_report)
    fig, ax = plt.subplots(figsize=(10, 4))
    null_report["pct"].plot(kind="barh", ax=ax, color="salmon")
    ax.set_xlabel("Missing %")
    ax.set_title("Columns with Missing Values")
    plt.tight_layout()
    plt.show()`),

    ...(highNullCols.length > 0
      ? [code(`# ── Handle high-null columns (>${20}% missing) ────────────────────
# Columns with >20% missing: ${highNullCols.join(", ")}
# Strategy options: drop, fill with median/mode, or flag as indicator

for col in ${JSON.stringify(highNullCols)}:
    if df[col].dtype in ["float64", "int64"]:
        df[col].fillna(df[col].median(), inplace=True)
    else:
        df[col].fillna(df[col].mode()[0] if not df[col].mode().empty else "Unknown", inplace=True)

print("Missing values handled ✓")`)]
      : []),

    ...(numericCols.length > 0
      ? [
          md(`## 3. Numeric Column Analysis`),
          code(`# ── Numeric distributions ───────────────────────────────────────────
numeric_cols = ${JSON.stringify(numericCols)}
n = len(numeric_cols)
fig, axes = plt.subplots(nrows=(n + 2) // 3, ncols=min(n, 3), figsize=(15, 4 * ((n + 2) // 3)))
axes = axes.flatten() if n > 1 else [axes]

for i, col in enumerate(numeric_cols):
    axes[i].hist(df[col].dropna(), bins=30, color="#7c3aed", alpha=0.7, edgecolor="white")
    axes[i].set_title(col, fontsize=10)
    axes[i].set_xlabel("")

for j in range(i + 1, len(axes)):
    axes[j].set_visible(False)

plt.suptitle("Numeric Column Distributions", y=1.02, fontsize=13)
plt.tight_layout()
plt.show()`),
          code(`# ── Skewness & outlier summary ──────────────────────────────────────
skew_df = pd.DataFrame({
    "skewness": df[numeric_cols].skew(),
    "kurtosis": df[numeric_cols].kurtosis(),
    "outlier_pct_iqr": [
        round(((df[c] < df[c].quantile(0.25) - 1.5 * (df[c].quantile(0.75) - df[c].quantile(0.25))) |
               (df[c] > df[c].quantile(0.75) + 1.5 * (df[c].quantile(0.75) - df[c].quantile(0.25)))).mean() * 100, 2)
        for c in numeric_cols
    ]
}).round(3)
print(skew_df.sort_values("skewness", key=abs, ascending=False))`),
        ]
      : []),

    ...(catCols.length > 0
      ? [
          md(`## 4. Categorical Column Analysis`),
          code(`# ── Categorical value counts ────────────────────────────────────────
cat_cols = ${JSON.stringify(catCols.slice(0, 8))}
fig, axes = plt.subplots(nrows=(len(cat_cols) + 1) // 2, ncols=2,
                          figsize=(14, 4 * ((len(cat_cols) + 1) // 2)))
axes = axes.flatten()

for i, col in enumerate(cat_cols):
    vc = df[col].value_counts().head(10)
    axes[i].barh(vc.index.astype(str), vc.values, color="#06b6d4", alpha=0.8)
    axes[i].set_title(col, fontsize=10)
    axes[i].invert_yaxis()

for j in range(i + 1, len(axes)):
    axes[j].set_visible(False)

plt.suptitle("Top Categorical Values", y=1.02, fontsize=13)
plt.tight_layout()
plt.show()`),
        ]
      : []),

    ...(numericCols.length > 1
      ? [
          md(`## 5. Correlation Analysis`),
          code(`# ── Correlation heatmap ─────────────────────────────────────────────
corr = df[${JSON.stringify(numericCols)}].corr()

mask = np.triu(np.ones_like(corr, dtype=bool))
fig, ax = plt.subplots(figsize=(max(8, len(numeric_cols)), max(6, len(numeric_cols) - 1)))
sns.heatmap(corr, mask=mask, annot=True, fmt=".2f", cmap="coolwarm",
            center=0, ax=ax, linewidths=0.5)
ax.set_title("Feature Correlation Matrix")
plt.tight_layout()
plt.show()

# Top correlated pairs
pairs = corr.unstack().reset_index()
pairs.columns = ["col1", "col2", "corr"]
pairs = pairs[pairs["col1"] < pairs["col2"]].sort_values("corr", key=abs, ascending=False)
print("Top 10 correlated pairs:")
print(pairs.head(10))`),
        ]
      : []),

    md(`## 6. AI-Generated Analysis\n\n${report.slice(0, 1500)}...`),

    ...(aiCode ? [md("## 7. AI-Generated Modelling Pipeline"), code(aiCode)] : []),

    md(`## 8. Next Steps\n\n- Clean remaining nulls and fix data types\n- Engineer features based on correlation findings\n- Split data: train/validation/test (70/15/15)\n- Train baseline model and measure performance\n- Iterate: feature selection, hyperparameter tuning\n- Monitor for data drift in production\n\n---\n*Generated by GadaaLabs DataLab · gadaalabs.com*`),
  ];

  const notebook = {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: { display_name: "Python 3", language: "python", name: "python3" },
      language_info: { name: "python", version: "3.11.0" },
    },
    cells,
  };

  return JSON.stringify(notebook, null, 2);
}

export function downloadNotebook(summary: DatasetSummary, aiCode: string, report: string) {
  const content = buildNotebook(summary, aiCode, report);
  const blob = new Blob([content], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  const name = summary.fileName.replace(/\.[^.]+$/, "");
  a.href = url;
  a.download = `${name}_analysis.ipynb`;
  a.click();
  URL.revokeObjectURL(url);
}
